# Generated by Django 4.2.1 on 2023-05-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_usermodelextended'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodelextended',
            name='image_url',
            field=models.CharField(default='no_image_url_available', max_length=100),
        ),
    ]
