# Generated by Django 4.2.1 on 2023-05-25 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_remove_roles_user_alter_usermodelextended_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_dst', models.CharField(max_length=200)),
                ('to_dst', models.CharField(max_length=200)),
                ('travel_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Flights',
            },
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('room_size', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.activities')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.flights')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.hotels')),
            ],
        ),
    ]
