# Generated by Django 4.2.1 on 2023-05-25 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0006_activities_flights_hotels_packages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packages',
            options={'verbose_name_plural': 'Packages'},
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.activities')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.flights')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.hotels')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Cancellations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.activities')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.flights')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.hotels')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cancellations',
            },
        ),
    ]
