# Generated by Django 4.2.1 on 2023-05-25 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_alter_packages_options_orders_cancellations'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellations',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 25, 10, 5, 10, 179975)),
        ),
        migrations.AddField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 25, 10, 5, 10, 178974)),
        ),
    ]
