# Generated by Django 4.2.1 on 2023-05-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_cancellations_created_at_orders_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
