# Generated by Django 4.2.1 on 2023-05-25 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_alter_cancellations_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='hotel',
        ),
        migrations.AddField(
            model_name='orders',
            name='is_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='packages',
            field=models.ManyToManyField(to='auth_app.packages'),
        ),
        migrations.CreateModel(
            name='CustomPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.activities')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.flights')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.hotels')),
            ],
            options={
                'verbose_name_plural': 'CustomPackages',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='custom_packages',
            field=models.ManyToManyField(to='auth_app.custompackages'),
        ),
    ]
