# Generated by Django 4.2.1 on 2023-05-28 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_orders_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodelextended',
            options={'verbose_name_plural': 'UserModelExtended'},
        ),
    ]
