# Generated by Django 4.2.1 on 2023-05-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_alter_usermodelextended_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='product_image_url',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png', max_length=200),
        ),
        migrations.AddField(
            model_name='flights',
            name='product_image_url',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png', max_length=200),
        ),
        migrations.AddField(
            model_name='hotels',
            name='product_image_url',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png', max_length=200),
        ),
    ]
