# Generated by Django 4.2.1 on 2023-05-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_activities_product_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='role_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
