# Generated by Django 4.2.1 on 2023-05-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0015_roles_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodelextended',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'User'), (2, 'Agent'), (3, 'Superuser')], null=True),
        ),
    ]
