# Generated by Django 4.2.1 on 2023-05-28 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_alter_usermodelextended_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodelextended',
            options={'permissions': (('can_create_hotels', 'User that has this permission enable can create hotel as individual product'), ('can_create_flights', 'User that has this permission enable can create flight as individual product'), ('can_create_activities', 'User that has this permission enable can create activities as individual product'), ('can_create_packages', 'User that has this permission enable can create package as individual product'), ('can_create_custom_packages', 'User that has this permission enable can create custom package as individual product'), ('can_edit_hotels', 'User that has this permission enable can edit hotel as individual product'), ('can_edit_flights', 'User that has this permission enable can edit flight as individual product'), ('can_edit_activities', 'User that has this permission enable can edit activity as individual product'), ('can_edit_packages', 'User that has this permission enable can edit package as individual product'), ('can_edit_custom_packages', 'User that has this permission enable can edit custom package as individual product'), ('can_delete_hotels', 'User that has this permission enable can delete hotel as individual product'), ('can_delete_flights', 'User that has this permission enable can delete flight as individual product'), ('can_delete_activities', 'User that has this permission enable can delete activity as individual product'), ('can_delete_packages', 'User that has this permission enable can delete package as individual product'), ('can_delete_custom_packages', 'User that has this permission enable can delete custom package as individual product'), ('can_remove_user', 'User that has this permission enable can remove any user except superuser'), ('can_create_user', 'User that has this permission enable can create new account an user (both agent and user)'), ('can_cancel_order', 'User that has this permission enable can cancel order based on user request'), ('can_place_order', 'User that has this permission enable can place new order'), ('can_create_new_permission', 'User that has this permission enabled can create new permissions for a specific role type'), ('can_create_new_role', 'User that has this permission enabled can create new role with permissions'), ('can_use_account', 'User need this permission enabled to be able to use his/her account')), 'verbose_name_plural': 'UserModelExtended'},
        ),
        migrations.RemoveField(
            model_name='cancellations',
            name='user',
        ),
        migrations.RemoveField(
            model_name='custompackages',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.AlterField(
            model_name='usermodelextended',
            name='image_url',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='usermodelextended',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.roles'),
        ),
    ]
