# Generated by Django 4.2.1 on 2023-05-28 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0017_alter_usermodelextended_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellations',
            name='user_model_extended',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth_app.usermodelextended'),
        ),
        migrations.AddField(
            model_name='custompackages',
            name='user_model_extended',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.usermodelextended'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_model_extended',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth_app.usermodelextended'),
        ),
        migrations.AddField(
            model_name='packages',
            name='user_model_extended',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth_app.usermodelextended'),
        ),
    ]
