# Generated by Django 4.2.1 on 2023-05-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0018_cancellations_user_model_extended_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodelextended',
            options={'permissions': (('can_use_account', 'User need this permission enabled to be able to use his/her account'),), 'verbose_name_plural': 'UserModelExtended'},
        ),
    ]
