# Generated by Django 4.2.1 on 2023-05-28 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0019_alter_usermodelextended_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Histories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, default=None, null=True)),
                ('description', models.CharField(blank=True, default='No description available', max_length=255, null=True)),
                ('user_model_extended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.usermodelextended')),
            ],
            options={
                'verbose_name_plural': 'Histories',
            },
        ),
    ]
