# Generated by Django 4.2.1 on 2023-05-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0021_alter_orders_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancellations',
            options={'permissions': (('add_cancellations_for_user', 'cancel for user'), ('view_cancellations_for_user', 'view cancellations for user'), ('delete_cancellations_for_user', 'delete cancellations for user'), ('change_cancellations_for_user', 'change cancellations for user')), 'verbose_name_plural': 'Cancellations'},
        ),
    ]
