# Generated by Django 4.2.1 on 2023-05-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0023_flights_user_model_exnteded'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='travel_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
