# Generated by Django 4.2.1 on 2023-05-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0025_flights_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
