# Generated by Django 4.2.1 on 2023-05-28 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0027_flights_description_hotels_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='activity',
        ),
        migrations.AddField(
            model_name='activities',
            name='user_model_exnteded',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.usermodelextended'),
        ),
        migrations.AddField(
            model_name='packages',
            name='activities',
            field=models.ManyToManyField(to='auth_app.activities'),
        ),
    ]
