# Generated by Django 4.2.1 on 2023-05-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0031_remove_custompackages_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompackages',
            name='flight_qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='custompackages',
            name='hotel_qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='packages',
            name='flight_qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='packages',
            name='hotel_qty',
            field=models.IntegerField(default=1),
        ),
    ]
