# Generated by Django 4.2.1 on 2023-05-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0032_custompackages_flight_qty_custompackages_hotel_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompackages',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='product_id',
        ),
        migrations.AddField(
            model_name='activities',
            name='price_id',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='product_id',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='price_id',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='product_id',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='price_id',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='product_id',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
