# Generated by Django 4.2.1 on 2023-05-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0034_flights_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
