# Generated by Django 4.2.1 on 2023-05-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0035_hotels_title_orders_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='price_id',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='price_id',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='price_id',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='product_id',
        ),
        migrations.AddField(
            model_name='hotels',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
