# Generated by Django 4.2.1 on 2023-05-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0038_flights_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
