# Generated by Django 4.2.1 on 2023-06-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0039_activities_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
