# Generated by Django 4.2.1 on 2023-06-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0041_packages_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='stock',
        ),
    ]
