# Generated by Django 4.2.1 on 2023-06-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0042_remove_activities_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='activity_count_list',
            field=models.TextField(null=True),
        ),
    ]
