# Generated by Django 4.2.1 on 2023-06-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0043_packages_activity_count_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
