# Generated by Django 4.2.1 on 2023-06-02 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0044_packages_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='activities',
            field=models.ManyToManyField(blank=True, null=True, to='auth_app.activities'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.flights'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.hotels'),
        ),
    ]
