# Generated by Django 4.2.1 on 2023-06-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0045_alter_packages_activities_alter_packages_flight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='activity_count_list',
        ),
    ]
