# Generated by Django 4.2.1 on 2023-06-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0046_remove_packages_activity_count_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
