# Generated by Django 4.2.1 on 2023-06-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0047_packages_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
