# Generated by Django 4.2.1 on 2023-06-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0048_packages_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='product_image_url',
        ),
    ]
