# Generated by Django 4.2.1 on 2023-06-02 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0050_custompackages_description_custompackages_is_done_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCustomPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_packages', models.ManyToManyField(to='auth_app.packages')),
                ('user_model_extended', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth_app.usermodelextended')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('packages', models.ManyToManyField(to='auth_app.packages')),
                ('user_model_extended', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth_app.usermodelextended')),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'permissions': (('add_orders_for_user', 'add orders for user'), ('change_orders_for_user', 'change orders for user'), ('delete_orders_for_user', 'delete orders for user'), ('view_orders_for_user', 'view orders for user')),
            },
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
