# Generated by Django 4.2.1 on 2023-06-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0051_ordercustompackages_orderpackages_delete_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpackages',
            options={'verbose_name_plural': 'Orders'},
        ),
    ]
