# Generated by Django 4.2.1 on 2023-06-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0052_alter_orderpackages_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercustompackages',
            name='custom_packages',
            field=models.ManyToManyField(to='auth_app.custompackages'),
        ),
    ]
