# Generated by Django 4.2.1 on 2023-06-02 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0054_alter_ordercustompackages_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercustompackages',
            name='user_model_extended',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth_app.usermodelextended'),
        ),
        migrations.AlterField(
            model_name='orderpackages',
            name='user_model_extended',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth_app.usermodelextended'),
        ),
    ]
