# Generated by Django 4.2.1 on 2023-06-02 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0055_alter_ordercustompackages_user_model_extended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercustompackages',
            name='custom_packages',
        ),
        migrations.RemoveField(
            model_name='orderpackages',
            name='packages',
        ),
        migrations.AddField(
            model_name='ordercustompackages',
            name='custom_packages',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth_app.custompackages'),
        ),
        migrations.AddField(
            model_name='orderpackages',
            name='packages',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth_app.packages'),
        ),
    ]
