# Generated by Django 4.2.1 on 2023-06-03 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0062_alter_usermodelextended_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='histories',
            old_name='description',
            new_name='status',
        ),
        migrations.AddField(
            model_name='histories',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='histories',
            name='other_user_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
