# Generated by Django 4.2.1 on 2023-06-03 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0063_rename_description_histories_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histories',
            name='other_user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
