# Generated by Django 4.2.1 on 2023-06-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0064_alter_histories_other_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='histories',
            old_name='other_user_id',
            new_name='other_user',
        ),
    ]
