# Generated by Django 4.2.1 on 2023-06-03 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0065_rename_other_user_id_histories_other_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriesCustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='No description available', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth_app.custompackages')),
                ('other_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_model_extended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.usermodelextended')),
            ],
            options={
                'verbose_name_plural': 'HistoriesCustomOrder',
            },
        ),
        migrations.CreateModel(
            name='HistoriesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='No description available', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth_app.orderpackages')),
                ('other_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_model_extended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.usermodelextended')),
            ],
            options={
                'verbose_name_plural': 'HistoriesOrder',
            },
        ),
        migrations.DeleteModel(
            name='Histories',
        ),
    ]
