# Generated by Django 4.2.1 on 2023-06-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0066_historiescustomorder_historiesorder_delete_histories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiesorder',
            old_name='custom_order',
            new_name='order',
        ),
    ]
