# Generated by Django 4.2.1 on 2023-06-03 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0067_rename_custom_order_historiesorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiescustomorder',
            name='custom_order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth_app.ordercustompackages'),
        ),
    ]
