# Generated by Django 4.2.1 on 2023-06-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0069_alter_ordercustompackages_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodelextended',
            name='forget_password_token',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
