# Generated by Django 4.2.1 on 2023-06-04 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0071_alter_historiesorder_other_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiescustomorder',
            name='other_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
